spring:
  application:
    name: api-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: ms-usuarios
          uri: ${MS_USUARIOS_URL:http://localhost:8081}
          predicates:
            - Path=/usuarios/**, /auth/**, /webhooks/**

        - id: ms-lancamentos
          uri: ${MS_LANCAMENTOS_URL:http://localhost:8083}
          predicates:
            - Path=/lancamentos/**, /cartoes/**

        - id: ms-centro-custo
          uri: ${MS_CENTRO_CUSTO_URL:http://localhost:8082}
          predicates:
            - Path=/centros-custo/**

        - id: ms-fluxo-caixa
          uri: ${MS_FLUXO_CAIXA_URL:http://localhost:8084}
          predicates:
            - Path=/fluxo-caixa/**

        - id: ms-contas
          uri: ${MS_CONTAS_URL:http://localhost:8087}
          predicates:
            - Path=/contas/**, /tipos-conta/**

        - id: ms-orcamento
          uri: ${MS_ORCAMENTO_URL:http://localhost:8088}
          predicates:
            - Path=/orcamentos/**, /metas-aplicacao/**

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

internal:
  secret: ${INTERNAL_SECRET}

ms-usuarios:
  url: ${MS_USUARIOS_URL:http://localhost:8081}